[project]
site_name = "FS Docs"
site_author = "Ramakrishna Sangamreddy"
site_url = "https://sramakrishnaa.github.io/fs-docs/"
copyright = "Copyright © 2026 Ramakrishna Sangamreddy"
repo_url = "https://github.com/sramakrishnaa/fs-docs"
repo_name = "sramakrishnaa/fs-docs"
edit_uri = "edit/main/docs/"

[project.theme]
name = "classic"
language = "en"
features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.tabs",
    "navigation.indexes",
    "navigation.top",
    "navigation.path",
    "toc.follow",
    "content.tabs.link",
    "content.code.copy",
    "content.code.annotate",
    "content.action.edit",
    "content.action.view",
    "search.highlight",
    "search.share",
    "search.suggest",
]

[project.theme.icon]
edit = "material/pencil"
view = "material/eye"
repo = "fontawesome/brands/github"

[project.theme.font]
text = "Inter"
code = "JetBrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
admonition = {}
"pymdownx.highlight" = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true }
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
"pymdownx.superfences" = {}
"pymdownx.tabbed" = { alternate_style = true }
"pymdownx.details" = {}
"pymdownx.emoji" = { emoji_index = "material.extensions.emoji.twemoji", emoji_generator = "material.extensions.emoji.to_svg" }

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/sramakrishnaa"