[project]
site_name = "FS Docs"
site_description = "Official documentation for FS Docs"
site_author = "Ramakrishna Sangamreddy"
site_url = "https://sramakrishnaa.github.io/fs-docs/"
copyright = "Copyright © 2026 Ramakrishna Sangamreddy"
repo_url = "https://github.com/sramakrishnaa/fs-docs"
repo_name = "sramakrishnaa/fs-docs"
edit_uri = "edit/main/docs/"

nav = [
    { "Java" = [
        { "Strings" = [
            "java/01-strings/01-introduction_to_strings.md",
            {"String Creation" = [
                "java/01-strings/02-string-creation/index.md",
                "java/01-strings/02-string-creation/01-string-literals.md",
                "java/01-strings/02-string-creation/02-using-new-keyword.md",
                "java/01-strings/02-string-creation/03-from-character-arrays.md",
                "java/01-strings/02-string-creation/04-from-byte-arrays.md",
                "java/01-strings/02-string-creation/05-from-stringbuilder-stringbuffer.md",
                "java/01-strings/02-string-creation/06-constructor-overload.md",
            ]}
        ]},
    ] },
]

[project.theme]
name = "material"
language = "en"
logo = "assets/logo.png"
favicon = "assets/favicon.png"
features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.tabs",
    # "navigation.sections",
    "navigation.indexes",
    "navigation.top",
    "navigation.path",
    "toc.follow",
    "content.tabs.link",
    "content.code.copy",
    "content.code.annotate",
    "content.code.select",
    "content.action.edit",
    "content.action.view",
    "content.tooltips",
    "content.footnote.tooltips",
    "search.highlight",
    "search.share",
    "search.suggest",
]

[project.theme.icon]
edit = "material/pencil"
view = "material/eye"
repo = "fontawesome/brands/github"

[project.theme.font]
text = "Inter"
code = "JetBrains Mono"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
admonition = {}
attr_list = {}
md_in_html = {}
footnotes = {}
toc = { toc_depth = 4 }
"pymdownx.details" = {}
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
"pymdownx.tabbed" = { alternate_style = true }
"pymdownx.highlight" = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true }

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/sramakrishnaa"
